const state={items:[],market:"ALL",favorites:JSON.parse(localStorage.getItem("mirai-favorites")||"[]"),currency:localStorage.getItem("mirai-currency")||"LOCAL",rates:{USD:1}};
const settings={theme:"paper",rise:"green",accent:"#0d6b55",...JSON.parse(localStorage.getItem("mirai-settings")||"{}")};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function applySettings(){document.documentElement.dataset.theme=settings.theme;document.documentElement.dataset.rise=settings.rise;document.documentElement.style.setProperty("--accent",settings.accent);$("#accent").value=settings.accent;$("#accent-value").textContent=settings.accent.toUpperCase();$$('[data-theme]').forEach(x=>x.classList.toggle('selected',x.dataset.theme===settings.theme));$$('[data-rise]').forEach(x=>x.classList.toggle('selected',x.dataset.rise===settings.rise));localStorage.setItem("mirai-settings",JSON.stringify(settings))}
function spark(points,positive){if(!points?.length)return"";const min=Math.min(...points),max=Math.max(...points),range=max-min||1;const d=points.map((p,i)=>`${i?'L':'M'} ${(i/(points.length-1))*180} ${48-((p-min)/range)*42}`).join(' ');return `<svg class="spark" viewBox="0 0 180 52" aria-label="今日走势"><path class="${positive?'up':'down'}" d="${d}"/><path class="base" d="M0 51H180"/></svg>`}
function converted(value,from){if(state.currency==='LOCAL'||!state.rates[from])return {value,currency:from};const usd=value/state.rates[from];return {value:state.currency==='USD'?usd:usd*(state.rates.CNY||1),currency:state.currency}}
function money(value,currency){const result=converted(Number(value),currency);return result.value.toLocaleString(undefined,{maximumFractionDigits:result.currency==='USD'?2:result.currency==='CNY'?2:0})+' '+result.currency}
function pointTime(value){const raw=String(value||'').replace(/\D/g,'');if(raw.length>=12)return `${raw.slice(0,4)}-${raw.slice(4,6)}-${raw.slice(6,8)} ${raw.slice(8,10)}:${raw.slice(10,12)}:${raw.length>=14?raw.slice(12,14):'00'}`;return String(value||'')}
function marketCapValue(value){if(typeof value==='number')return value;const text=String(value||'').replace(/,/g,'');const jo=Number((text.match(/([\d.]+)\s*조/)||[])[1]||0);const eok=Number((text.match(/([\d.]+)\s*억/)||[])[1]||0);if(jo||eok)return jo*1e12+eok*1e8;const plain=Number(text.replace(/[^\d.-]/g,''));return Number.isFinite(plain)&&plain>0?plain:null}
function marketCap(value,currency){const total=marketCapValue(value);if(!total)return value||'暂无数据';const result=converted(total,currency);if(result.currency==='KRW')return (result.value/1e12).toLocaleString('zh-CN',{maximumFractionDigits:2})+' 万亿韩元';if(result.value>=1e12)return (result.value/1e12).toLocaleString('zh-CN',{maximumFractionDigits:2})+' 万亿'+(result.currency==='USD'?'美元':'人民币');return (result.value/1e8).toLocaleString('zh-CN',{maximumFractionDigits:2})+' 亿'+(result.currency==='USD'?'美元':'人民币')}
function card(x){return `<article class="index-card"><div class="row"><div><span class="flag">${x.market}</span><h3>${x.name}</h3><small>${x.localName}</small></div><strong>${x.price.toLocaleString()}</strong></div><div class="row chart"><span class="${x.change>=0?'gain':'loss'}">${x.change>=0?'+':''}${x.changePercent.toFixed(2)}%</span>${spark(x.points,x.change>=0)}</div></article>`}
function stock(x){const fav=state.favorites.includes(x.id),shownChange=converted(x.change,x.currency);return `<article class="stock ${fav?'favorite':''}" data-detail="${x.symbol}" role="button" tabindex="0" aria-label="查看 ${x.name} 详情"><div class="company"><span class="flag">${x.market}</span><div><h3>${x.name}</h3><small>${x.localName} · ${x.symbol}</small></div></div><strong>${money(x.price,x.currency)}</strong><span class="${x.change>=0?'gain':'loss'}">${x.change>=0?'+':''}${Math.abs(shownChange.value).toLocaleString(undefined,{maximumFractionDigits:2})} ${shownChange.currency}<small>${x.changePercent>=0?'+':''}${x.changePercent.toFixed(2)}%</small></span>${spark(x.points,x.change>=0)}<button class="star" data-favorite="${x.id}" aria-label="${fav?'取消收藏':'收藏'}${x.name}">${fav?'★':'☆'}</button></article>`}
function render(){const items=state.items.filter(x=>state.market==='ALL'||x.market===state.market).sort((a,b)=>Number(state.favorites.includes(b.id))-Number(state.favorites.includes(a.id)));$("#indexes").innerHTML=items.filter(x=>x.kind==='index').map(card).join('');$("#stocks").innerHTML=items.filter(x=>x.kind==='stock').map(stock).join('');const ups=state.items.filter(x=>x.changePercent>0).length;$("#sentiment").textContent=ups>=state.items.length/2?'偏多':'偏空';$("#sentiment-count").textContent=`上涨标的 ${ups} / ${state.items.length}`;$("#sentiment-bar").style.width=`${state.items.length?ups/state.items.length*100:0}%`;$$('[data-favorite]').forEach(b=>b.onclick=e=>{e.stopPropagation();state.favorites=state.favorites.includes(b.dataset.favorite)?state.favorites.filter(x=>x!==b.dataset.favorite):[...state.favorites,b.dataset.favorite];localStorage.setItem('mirai-favorites',JSON.stringify(state.favorites));render()});$$('[data-detail]').forEach(row=>{row.onclick=()=>openDetail(row.dataset.detail);row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openDetail(row.dataset.detail)}}})}
function fullChart(points,labels=[],currency='KRW'){if(!points?.length||points.length<3)return '<p>暂时没有足够的日内数据，避免用两个报价点绘制误导性直线。</p>';const min=Math.min(...points),max=Math.max(...points),range=max-min||1,w=820,h=270,pad=18;const coords=points.map((value,index)=>[pad+(index/Math.max(1,points.length-1))*(w-pad*2),h-pad-((value-min)/range)*(h-pad*2)]);const line=coords.map((point,index)=>`${index?'L':'M'}${point[0].toFixed(1)},${point[1].toFixed(1)}`).join(' ');const area=line+` L${w-pad},${h-pad} L${pad},${h-pad} Z`;const hits=coords.map((point,index)=>{const label=labels[index]?pointTime(labels[index]):'点位 '+(index+1);return `<circle class="chart-hit" tabindex="0" cx="${point[0].toFixed(1)}" cy="${point[1].toFixed(1)}" r="4" data-label="${label}" data-value="${points[index]}" data-currency="${currency}"><title>${label} · ${points[index]}</title></circle>`}).join('');return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="完整日内价格走势"><path class="chart-base" d="M${pad},${h-pad}H${w-pad}"/><path class="chart-area" d="${area}"/><path class="chart-line" d="${line}"/>${hits}</svg>`}
function wireChartPoints(){$$('.chart-hit').forEach(point=>{const show=()=>{$('#detail-point').textContent=point.dataset.label+' · '+money(Number(point.dataset.value),point.dataset.currency)};point.onmouseenter=show;point.onclick=show;point.onfocus=show})}
function parseDetailPayload(text){try{return JSON.parse(text)}catch(error){const points=[],labels=[],pattern=/<item\s+data=["']([^"']+)["']/g;let match;while((match=pattern.exec(text))!==null){const fields=match[1].split('|'),close=Number(fields[4]);if(Number.isFinite(close)){labels.push(fields[0]);points.push(close)}}if(points.length)return {points,labels,source:'Naver intraday XML',completeDay:true};const title=(text.match(/<title[^>]*>([^<]+)<\/title>/i)||[])[1];throw Error(title?`详情源返回网页：${title}`:'详情源返回了无法识别的内容')}}
async function openDetail(symbol){const item=state.items.find(x=>x.symbol===symbol);if(!item)return;$("#detail").hidden=false;document.body.style.overflow='hidden';$("#detail-market").textContent=(item.market==='KR'?'韩国市场':'日本市场')+' · '+item.source;$("#detail-name").textContent=item.name;$("#detail-symbol").textContent=item.localName+' · '+item.symbol;$("#detail-price").textContent=money(item.price,item.currency);const shownChange=converted(item.change,item.currency);$("#detail-change").className=item.change>=0?'gain':'loss';$("#detail-change").textContent=(item.change>=0?'+':'')+Math.abs(shownChange.value).toLocaleString(undefined,{maximumFractionDigits:2})+' '+shownChange.currency+' · '+(item.changePercent>=0?'+':'')+item.changePercent.toFixed(2)+'%';$("#detail-pe").textContent=item.pe||'暂无数据';$("#detail-cap").textContent=item.marketCap||'暂无数据';$("#detail-point").textContent='将鼠标移到曲线上';$("#detail-chart").innerHTML='<p>正在按需获取完整日内走势…</p>';$("#detail-source").textContent='正在连接详情数据源';try{const response=await fetch('/api/quote?mode=detail&symbol='+encodeURIComponent(symbol),{headers:{Accept:'application/json'}});const contentType=response.headers.get('content-type')||'';if(!contentType.toLowerCase().includes('application/json'))throw Error('详情接口被静态页面接管，请重新部署最新版本');const text=await response.text();const data=parseDetailPayload(text);if(!response.ok)throw Error(data.error||'详情接口不可用');$("#detail-chart").innerHTML=fullChart(data.points,data.labels,item.currency);wireChartPoints();$("#detail-source").textContent=(data.source||'日内走势')+' · '+data.points.length+' 个数据点'}catch(error){$("#detail-chart").innerHTML=`<p>${error.message}</p>`;$("#detail-source").textContent='完整日内走势暂不可用'} }
function closeDetail(){$("#detail").hidden=true;document.body.style.overflow=''}
$("#close-detail").onclick=closeDetail;$("#detail").onclick=e=>{if(e.target.id==='detail')closeDetail()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$("#detail").hidden)closeDetail()});
$("#currency-select").value=state.currency;$("#currency-select").onchange=e=>{state.currency=e.target.value;localStorage.setItem('mirai-currency',state.currency);render();if(!$("#detail").hidden)closeDetail()};fetch('/api/fx').then(r=>r.ok?r.json():Promise.reject()).then(data=>{state.rates=data.rates||state.rates;render()}).catch(()=>{});
$$('[data-market]').forEach(b=>b.onclick=()=>{state.market=b.dataset.market;$$('[data-market]').forEach(x=>x.classList.toggle('active',x===b));render()});
$("#open-settings").onclick=()=>$("#settings").hidden=false;$("#close-settings").onclick=()=>$("#settings").hidden=true;$("#settings").onclick=e=>{if(e.target.id==='settings')e.currentTarget.hidden=true};$$('[data-theme]').forEach(b=>b.onclick=()=>{settings.theme=b.dataset.theme;applySettings()});$$('[data-rise]').forEach(b=>b.onclick=()=>{settings.rise=b.dataset.rise;applySettings();render()});$("#accent").oninput=e=>{settings.accent=e.target.value;applySettings()};applySettings();
const parseDetailPayloadBase=parseDetailPayload;parseDetailPayload=function(text){const data=parseDetailPayloadBase(text);if(data.pe)$("#detail-pe").textContent=data.pe;if(data.marketCap){const symbol=$("#detail-symbol").textContent.split(' · ').pop();const item=state.items.find(x=>x.symbol===symbol);$("#detail-cap").textContent=marketCap(data.marketCap,item?.currency||'KRW')}return data};
const quoteSymbols=['^N225','^TOPX','^KS11','^KQ11','6758.T','8035.T','6857.T','6861.T','9984.T','6723.T','6146.T','7974.T','005930.KS','000660.KS','035420.KS','035720.KS','066570.KS','009150.KS','042700.KS','373220.KS'];
Promise.allSettled(quoteSymbols.map(symbol=>fetch('/api/quote?symbol='+encodeURIComponent(symbol)).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d.item}))).then(results=>{state.items=results.filter(result=>result.status==='fulfilled').map(result=>result.value);const failed=results.length-state.items.length;if(!state.items.length)throw Error(results.find(result=>result.status==='rejected')?.reason?.message||'接口未返回数据');const kr=state.items.filter(item=>item.market==='KR').length,jp=state.items.filter(item=>item.market==='JP').length;$("#data-state").textContent='韩国 '+kr+'/10 · 日本 '+jp+'/10'+(failed?' · '+failed+' 项失败':'');$("#updated").textContent='更新 '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});render()}).catch(error=>{$("#data-state").textContent='接口错误：'+error.message;$("#sentiment").textContent='离线'});
