const state={items:[],market:"ALL",favorites:JSON.parse(localStorage.getItem("mirai-favorites")||"[]")};
const settings={theme:"paper",rise:"green",accent:"#0d6b55",...JSON.parse(localStorage.getItem("mirai-settings")||"{}")};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function applySettings(){document.documentElement.dataset.theme=settings.theme;document.documentElement.dataset.rise=settings.rise;document.documentElement.style.setProperty("--accent",settings.accent);$("#accent").value=settings.accent;$("#accent-value").textContent=settings.accent.toUpperCase();$$('[data-theme]').forEach(x=>x.classList.toggle('selected',x.dataset.theme===settings.theme));$$('[data-rise]').forEach(x=>x.classList.toggle('selected',x.dataset.rise===settings.rise));localStorage.setItem("mirai-settings",JSON.stringify(settings))}
function spark(points,positive){if(!points?.length)return"";const min=Math.min(...points),max=Math.max(...points),range=max-min||1;const d=points.map((p,i)=>`${i?'L':'M'} ${(i/(points.length-1))*180} ${48-((p-min)/range)*42}`).join(' ');return `<svg class="spark" viewBox="0 0 180 52" aria-label="今日走势"><path class="${positive?'up':'down'}" d="${d}"/><path class="base" d="M0 51H180"/></svg>`}
function card(x){return `<article class="index-card"><div class="row"><div><span class="flag">${x.market}</span><h3>${x.name}</h3><small>${x.localName}</small></div><strong>${x.price.toLocaleString()}</strong></div><div class="row chart"><span class="${x.change>=0?'gain':'loss'}">${x.change>=0?'+':''}${x.changePercent.toFixed(2)}%</span>${spark(x.points,x.change>=0)}</div></article>`}
function stock(x){const fav=state.favorites.includes(x.id);return `<article class="stock ${fav?'favorite':''}" data-detail="${x.symbol}" role="button" tabindex="0" aria-label="查看 ${x.name} 详情"><div class="company"><span class="flag">${x.market}</span><div><h3>${x.name}</h3><small>${x.localName} · ${x.symbol}</small></div></div><strong>${x.price.toLocaleString()} <small>${x.currency}</small></strong><span class="${x.change>=0?'gain':'loss'}">${x.change>=0?'+':''}${x.change.toLocaleString()}<small>${x.changePercent>=0?'+':''}${x.changePercent.toFixed(2)}%</small></span>${spark(x.points,x.change>=0)}<button class="star" data-favorite="${x.id}" aria-label="${fav?'取消收藏':'收藏'}${x.name}">${fav?'★':'☆'}</button></article>`}
function render(){const items=state.items.filter(x=>state.market==='ALL'||x.market===state.market).sort((a,b)=>Number(state.favorites.includes(b.id))-Number(state.favorites.includes(a.id)));$("#indexes").innerHTML=items.filter(x=>x.kind==='index').map(card).join('');$("#stocks").innerHTML=items.filter(x=>x.kind==='stock').map(stock).join('');const ups=state.items.filter(x=>x.changePercent>0).length;$("#sentiment").textContent=ups>=state.items.length/2?'偏多':'偏空';$("#sentiment-count").textContent=`上涨标的 ${ups} / ${state.items.length}`;$("#sentiment-bar").style.width=`${state.items.length?ups/state.items.length*100:0}%`;$$('[data-favorite]').forEach(b=>b.onclick=e=>{e.stopPropagation();state.favorites=state.favorites.includes(b.dataset.favorite)?state.favorites.filter(x=>x!==b.dataset.favorite):[...state.favorites,b.dataset.favorite];localStorage.setItem('mirai-favorites',JSON.stringify(state.favorites));render()});$$('[data-detail]').forEach(row=>{row.onclick=()=>openDetail(row.dataset.detail);row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openDetail(row.dataset.detail)}}})}
function fullChart(points){if(!points?.length)return '<p>暂时没有可用的日内走势数据</p>';const min=Math.min(...points),max=Math.max(...points),range=max-min||1,w=820,h=270,pad=18;const coords=points.map((value,index)=>[pad+(index/Math.max(1,points.length-1))*(w-pad*2),h-pad-((value-min)/range)*(h-pad*2)]);const line=coords.map((point,index)=>`${index?'L':'M'}${point[0].toFixed(1)},${point[1].toFixed(1)}`).join(' ');const area=line+` L${w-pad},${h-pad} L${pad},${h-pad} Z`;return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="完整日内价格走势"><path class="chart-base" d="M${pad},${h-pad}H${w-pad}"/><path class="chart-area" d="${area}"/><path class="chart-line" d="${line}"/></svg>`}
async function openDetail(symbol){const item=state.items.find(x=>x.symbol===symbol);if(!item)return;$("#detail").hidden=false;document.body.style.overflow='hidden';$("#detail-market").textContent=(item.market==='KR'?'韩国市场':'日本市场')+' · '+item.source;$("#detail-name").textContent=item.name;$("#detail-symbol").textContent=item.localName+' · '+item.symbol;$("#detail-price").textContent=item.price.toLocaleString()+' '+item.currency;$("#detail-change").className=item.change>=0?'gain':'loss';$("#detail-change").textContent=(item.change>=0?'+':'')+item.change.toLocaleString()+' · '+(item.changePercent>=0?'+':'')+item.changePercent.toFixed(2)+'%';$("#detail-chart").innerHTML='<p>正在按需获取完整日内走势…</p>';$("#detail-source").textContent='正在连接详情数据源';try{const response=await fetch('/api/detail?symbol='+encodeURIComponent(symbol));const data=await response.json();if(!response.ok)throw Error(data.error||'详情接口不可用');$("#detail-chart").innerHTML=fullChart(data.points);$("#detail-source").textContent=data.source+' · '+data.points.length+' 个数据点'}catch(error){$("#detail-chart").innerHTML=fullChart(item.points)+`<p>${error.message}，当前显示可用报价走势。</p>`;$("#detail-source").textContent='备用走势'} }
function closeDetail(){$("#detail").hidden=true;document.body.style.overflow=''}
$("#close-detail").onclick=closeDetail;$("#detail").onclick=e=>{if(e.target.id==='detail')closeDetail()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$("#detail").hidden)closeDetail()});
$$('[data-market]').forEach(b=>b.onclick=()=>{state.market=b.dataset.market;$$('[data-market]').forEach(x=>x.classList.toggle('active',x===b));render()});
$("#open-settings").onclick=()=>$("#settings").hidden=false;$("#close-settings").onclick=()=>$("#settings").hidden=true;$("#settings").onclick=e=>{if(e.target.id==='settings')e.currentTarget.hidden=true};$$('[data-theme]').forEach(b=>b.onclick=()=>{settings.theme=b.dataset.theme;applySettings()});$$('[data-rise]').forEach(b=>b.onclick=()=>{settings.rise=b.dataset.rise;applySettings();render()});$("#accent").oninput=e=>{settings.accent=e.target.value;applySettings()};applySettings();
const quoteSymbols=['^N225','^TOPX','^KS11','^KQ11','6758.T','8035.T','6857.T','6861.T','9984.T','6723.T','6146.T','7974.T','005930.KS','000660.KS','035420.KS','035720.KS','066570.KS','009150.KS','042700.KS','373220.KS'];
Promise.allSettled(quoteSymbols.map(symbol=>fetch('/api/quote?symbol='+encodeURIComponent(symbol)).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d.item}))).then(results=>{state.items=results.filter(result=>result.status==='fulfilled').map(result=>result.value);const failed=results.length-state.items.length;if(!state.items.length)throw Error(results.find(result=>result.status==='rejected')?.reason?.message||'接口未返回数据');const kr=state.items.filter(item=>item.market==='KR').length,jp=state.items.filter(item=>item.market==='JP').length;$("#data-state").textContent='韩国 '+kr+'/10 · 日本 '+jp+'/10'+(failed?' · '+failed+' 项失败':'');$("#updated").textContent='更新 '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});render()}).catch(error=>{$("#data-state").textContent='接口错误：'+error.message;$("#sentiment").textContent='离线'});
