const symbols=["^N225","^TOPX","^KS11","^KQ11","6758.T","8035.T","6857.T","6861.T","9984.T","6723.T","6146.T","7974.T","005930.KS","000660.KS","035420.KS","035720.KS","066570.KS","009150.KS","042700.KS","373220.KS"];
const info={"^N225":["nikkei","日经 225","JP","index"],"^TOPX":["topix","TOPIX","JP","index"],"^KS11":["kospi","KOSPI","KR","index"],"^KQ11":["kosdaq","KOSDAQ","KR","index"],"6758.T":["sony","索尼集团","JP","stock"],"8035.T":["tel","东京电子","JP","stock"],"6857.T":["advantest","爱德万测试","JP","stock"],"6861.T":["keyence","基恩士","JP","stock"],"9984.T":["softbank","软银集团","JP","stock"],"6723.T":["renesas","瑞萨电子","JP","stock"],"6146.T":["disco","迪思科","JP","stock"],"7974.T":["nintendo","任天堂","JP","stock"],"005930.KS":["samsung","三星电子","KR","stock"],"000660.KS":["skhynix","SK 海力士","KR","stock"],"035420.KS":["naver","NAVER","KR","stock"],"035720.KS":["kakao","Kakao","KR","stock"],"066570.KS":["lge","LG电子","KR","stock"],"009150.KS":["semco","三星电机","KR","stock"],"042700.KS":["hanmi","韩美半导体","KR","stock"],"373220.KS":["lges","LG新能源","KR","stock"]};
async function market(){const settled=await Promise.allSettled(symbols.map(async symbol=>{const r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=1d&interval=5m`,{headers:{"User-Agent":"Mozilla/5.0"}});if(!r.ok)throw Error();const j=await r.json(),c=j.chart.result?.[0],m=c?.meta,pts=(c?.indicators?.quote?.[0]?.close||[]).filter(n=>typeof n==='number');if(!m||!pts.length)throw Error();const[id,name,market,kind]=info[symbol],prev=m.chartPreviousClose||m.previousClose||pts[0],price=m.regularMarketPrice||pts.at(-1),change=price-prev;return{id,name,localName:m.longName||m.shortName||name,symbol,market,kind,price,change,changePercent:change/prev*100,currency:m.currency||(market==='JP'?'JPY':'KRW'),points:pts.filter((_,i)=>i%Math.max(1,Math.floor(pts.length/24))===0).slice(-24)}}));return new Response(JSON.stringify({items:settled.filter(x=>x.status==='fulfilled').map(x=>x.value),updatedAt:new Date().toISOString()}),{headers:{'content-type':'application/json;charset=UTF-8','cache-control':'public,max-age=60'}})}
async function handleRequest(request){
  const url=new URL(request.url);
  if(url.pathname==='/api/market')return market();
  return new Response('Not Found',{status:404,headers:{'content-type':'text/plain;charset=UTF-8'}});
}
addEventListener('fetch',event=>event.respondWith(handleRequest(event.request)));
